# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('image', models.URLField(blank=True, default='')),
                ('estprice', models.FloatField(blank=True, default=None)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('image', models.URLField(blank=True, default='')),
                ('steps', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('l', 'liter'), ('dl', 'deciliter'), ('cl', 'centiliter'), ('tsk', 'teske'), ('spsk', 'spiseske'), ('stk', 'styk')], max_length=32)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipedb.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipedb.Recipe')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
