# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipedb', '0002_auto_20170914_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipedb.Recipe'),
        ),
    ]
